<?xml version="1.0" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

    <material name="light_grey_transparent">
      <color rgba="0.75 0.75 0.75 0.5" />
    </material>

    <xacro:macro name="hand_box" params="name width depth height prefix">
      <link name="${prefix}box_base_attach">
        <visual>
          <origin xyz="0.0 0.0 ${height / 2}" rpy="0.0 0.0 0.0" />
          <geometry name="${name}">
            <box size="${width} ${depth} ${height}"/>
          </geometry>
          <material name="light_grey_transparent"/>
        </visual>
        <collision>
          <origin xyz="0.0 0.0 ${height / 2}" rpy="0.0 0.0 0.0" />
          <geometry name="${name}">
            <box size="${width} ${depth} ${height}"/>
          </geometry>
        </collision>
      </link>
      <joint name="${prefix}hand_ee_fixed_joint" type="fixed">
        <parent link="${prefix}hand_base_attach" />
        <child link = "${prefix}hand_manipulator" />
        <origin xyz="0.0 0.0 0.10" rpy="0.0 0.0 0.0" />
      </joint>
      <link name="${prefix}hand_manipulator" />
    </xacro:macro>

</robot>
