# Software License Agreement (BSD License)
# Copyright © 2022-2023 belongs to Shadow Robot Company Ltd.
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification,
# are permitted provided that the following conditions are met:
#   1. Redistributions of source code must retain the above copyright notice,
#      this list of conditions and the following disclaimer.
#   2. Redistributions in binary form must reproduce the above copyright notice,
#      this list of conditions and the following disclaimer in the documentation
#      and/or other materials provided with the distribution.
#   3. Neither the name of Shadow Robot Company Ltd nor the names of its contributors
#      may be used to endorse or promote products derived from this software without
#      specific prior written permission.
#
# This software is provided by Shadow Robot Company Ltd "as is" and any express
# or implied warranties, including, but not limited to, the implied warranties of
# merchantability and fitness for a particular purpose are disclaimed. In no event
# shall the copyright holder be liable for any direct, indirect, incidental, special,
# exemplary, or consequential damages (including, but not limited to, procurement of
# substitute goods or services; loss of use, data, or profits; or business interruption)
# however caused and on any theory of liability, whether in contract, strict liability,
# or tort (including negligence or otherwise) arising in any way out of the use of this
# software, even if advised of the possibility of such damage.

sh_rh_ffj0_position_controller:
  joint: rh_FFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_ffj3_position_controller:
  joint: rh_FFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_ffj4_position_controller:
  joint: rh_FFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj0_position_controller:
  joint: rh_LFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj3_position_controller:
  joint: rh_LFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj4_position_controller:
  joint: rh_LFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_lfj5_position_controller:
  joint: rh_LFJ5
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj0_position_controller:
  joint: rh_MFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj3_position_controller:
  joint: rh_MFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_mfj4_position_controller:
  joint: rh_MFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj0_position_controller:
  joint: rh_RFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj3_position_controller:
  joint: rh_RFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_rfj4_position_controller:
  joint: rh_RFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj1_position_controller:
  joint: rh_THJ1
  pid:
    d: 0.0 #otherwise oscillates
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj2_position_controller:
  joint: rh_THJ2
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj3_position_controller:
  joint: rh_THJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj4_position_controller:
  joint: rh_THJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_thj5_position_controller:
  joint: rh_THJ5
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_wrj1_position_controller:
  joint: rh_WRJ1
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_rh_wrj2_position_controller:
  joint: rh_WRJ2
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController



sh_lh_ffj0_position_controller:
  joint: lh_FFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_ffj3_position_controller:
  joint: lh_FFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_ffj4_position_controller:
  joint: lh_FFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_lfj0_position_controller:
  joint: lh_LFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_lfj3_position_controller:
  joint: lh_LFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_lfj4_position_controller:
  joint: lh_LFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_lfj5_position_controller:
  joint: lh_LFJ5
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_mfj0_position_controller:
  joint: lh_MFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_mfj3_position_controller:
  joint: lh_MFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_mfj4_position_controller:
  joint: lh_MFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_rfj0_position_controller:
  joint: lh_RFJ0
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_rfj3_position_controller:
  joint: lh_RFJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_rfj4_position_controller:
  joint: lh_RFJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_thj1_position_controller:
  joint: lh_THJ1
  pid:
    d: 0.0 #otherwise oscillates
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_thj2_position_controller:
  joint: lh_THJ2
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_thj3_position_controller:
  joint: lh_THJ3
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 10.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_thj4_position_controller:
  joint: lh_THJ4
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_thj5_position_controller:
  joint: lh_THJ5
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_wrj1_position_controller:
  joint: lh_WRJ1
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController

sh_lh_wrj2_position_controller:
  joint: lh_WRJ2
  pid:
    d: 1.5
    i: 0.5
    i_clamp: 1.5
    p: 5.0
    position_deadband: 0.0
    max_force: 30.0
  type: sr_mechanism_controllers/SrhJointPositionController
