ra_group_position_controller:
  type: "position_controllers/JointGroupPositionController"
  joints:
    - ra_shoulder_pan_joint
    - ra_shoulder_lift_joint
    - ra_elbow_joint
    - ra_wrist_1_joint
    - ra_wrist_2_joint
    - ra_wrist_3_joint
    - rh_WRJ1
    - rh_WRJ2
