ra_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - ra_shoulder_pan_joint
    - ra_shoulder_lift_joint
    - ra_elbow_joint
    - ra_wrist_1_joint
    - ra_wrist_2_joint
    - ra_wrist_3_joint
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 1.0
      ra_shoulder_pan_joint: {trajectory: 0.3, goal: 0.1}
      ra_shoulder_lift_joint: {trajectory: 0.3, goal: 0.1}
      ra_elbow_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_1_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_2_joint: {trajectory: 0.3, goal: 0.1}
      ra_wrist_3_joint: {trajectory: 0.3, goal: 0.1}
  stop_trajectory_duration: 0.5
  state_publish_rate:  25
  action_monitor_rate: 10
  allow_partial_joints_goal: true
