robot:
  name: bimanual_shadowhand_motor
  manipulators:
    right_manipulator:
      side: right
      hand:
        name: sr_hand.urdf.xacro
    left_manipulator:
      side: left
      hand:
        name: sr_hand.urdf.xacro
