robot:
  name: ursrh
  manipulators:
    left_manipulator:
      side: left
      arm:
        name: ur5e
        main_group: manipulator
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
      hand: True
