robot:
  name: ursr
  manipulators:
    right_manipulator:
      side: left
      arm:
        name: ur5e
        main_group: manipulator
        moveit_path:
          package: sr_multi_moveit_config
          relative_path: /config/ur
        extra_groups_config_path: /config
        group_states:
          - home
          - up
        hand: False

ra_sr_ur_robot_hw:
  # No hand
  payload_mass_kg: 0.0
