rh_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - rh_FFJ1
    - rh_FFJ2
    - rh_FFJ3
    - rh_FFJ4
    - rh_LFJ1
    - rh_LFJ2
    - rh_LFJ3
    - rh_LFJ4
    - rh_LFJ5
    - rh_MFJ1
    - rh_MFJ2
    - rh_MFJ3
    - rh_MFJ4
    - rh_RFJ1
    - rh_RFJ2
    - rh_RFJ3
    - rh_RFJ4
    - rh_THJ1
    - rh_THJ2
    - rh_THJ3
    - rh_THJ4
    - rh_THJ5
  constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 10.0
      rh_FFJ1: {trajectory: 2.0, goal: 2.1}
      rh_FFJ2: {trajectory: 2.0, goal: 2.1}
      rh_FFJ3: {trajectory: 2.0, goal: 2.1}
      rh_FFJ4: {trajectory: 2.0, goal: 2.1}
      rh_LFJ1: {trajectory: 2.0, goal: 2.1}
      rh_LFJ2: {trajectory: 2.0, goal: 2.1}
      rh_LFJ3: {trajectory: 2.0, goal: 2.1}
      rh_LFJ4: {trajectory: 2.0, goal: 2.1}
      rh_LFJ5: {trajectory: 2.0, goal: 2.1}
      rh_MFJ1: {trajectory: 2.0, goal: 2.1}
      rh_MFJ2: {trajectory: 2.0, goal: 2.1}
      rh_MFJ3: {trajectory: 2.0, goal: 2.1}
      rh_MFJ4: {trajectory: 2.0, goal: 2.1}
      rh_RFJ1: {trajectory: 2.0, goal: 2.1}
      rh_RFJ2: {trajectory: 2.0, goal: 2.1}
      rh_RFJ3: {trajectory: 2.0, goal: 2.1}
      rh_RFJ4: {trajectory: 2.0, goal: 2.1}
      rh_THJ1: {trajectory: 2.0, goal: 2.1}
      rh_THJ2: {trajectory: 2.0, goal: 2.1}
      rh_THJ3: {trajectory: 2.0, goal: 2.1}
      rh_THJ4: {trajectory: 2.0, goal: 2.1}
      rh_THJ5: {trajectory: 2.0, goal: 2.1}
      rh_WRJ1: {trajectory: 2.0, goal: 2.1}
      rh_WRJ2: {trajectory: 2.0, goal: 2.1}
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true
