stomp/right_arm:
  group_name: right_arm
  optimization:
    num_timesteps: 20
    num_dimensions: 6
    num_iterations: 500
    num_iterations_after_valid: 0
    delta_t: 0.1
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.1
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.3, 0.3, 0.3, 0.1, 0.1, 0.1]
    cost_functions:
      - class: stomp_moveit/CollisionCheck
        collision_penalty: 1.0
        cost_weight: 1.0
        kernel_window_percentage: 0.2
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [191, 0, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
stomp/right_arm_and_wrist:
  group_name: right_arm_and_wrist
  optimization:
    num_timesteps: 20
    num_dimensions: 8
    num_iterations: 500
    num_iterations_after_valid: 0
    delta_t: 0.1
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.1
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.3, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1]
    cost_functions:
      - class: stomp_moveit/CollisionCheck
        collision_penalty: 1.0
        cost_weight: 1.0
        kernel_window_percentage: 0.2
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [191, 0, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
stomp/right_arm_and_hand:
  group_name: right_arm_and_hand
  optimization:
    num_timesteps: 20
    num_dimensions: 30
    num_iterations: 500
    num_iterations_after_valid: 0
    delta_t: 0.1
    num_rollouts: 10
    max_rollouts: 100
    initialization_method: 1 #[1 : LINEAR_INTERPOLATION, 2 : CUBIC_POLYNOMIAL, 3 : MININUM_CONTROL_COST
    control_cost_weight: 0.1
  task:
    noise_generator:
      - class: stomp_moveit/NormalDistributionSampling
        stddev: [0.3, 0.3, 0.3, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1, 0.1]
    cost_functions:
      - class: stomp_moveit/CollisionCheck
        collision_penalty: 1.0
        cost_weight: 1.0
        kernel_window_percentage: 0.2
    noisy_filters:
      - class: stomp_moveit/JointLimits
        lock_start: True
        lock_goal: True
      - class: stomp_moveit/MultiTrajectoryVisualization
        line_width: 0.02
        rgb: [0, 255, 0]
        marker_array_topic: stomp_trajectories
        marker_namespace: noisy
    update_filters:
      - class: stomp_moveit/ControlCostProjectionMatrix
      - class: stomp_moveit/TrajectoryVisualization
        line_width: 0.02
        rgb: [191, 0, 255]
        error_rgb: [255, 0, 0]
        publish_intermediate: True
        marker_topic: stomp_trajectory
        marker_namespace: optimized
